defaults: &defaults

  facebook:
    app_id: ENV['FB_ID']
    secret_key: ENV['FB_KEY']

  vk:
    api_key: ENV['VK_ID']
    api_secret: ENV['VK_KEY']

  twitter:
    api_key: ENV['TW_ID']
    api_secret: ENV['TW_KEY']

  google:
    client_id: 470546575625-rb9k6u30acptfhkk58uvead48tjoj91o.apps.googleusercontent.com
    client_secret: xpC7jfnqDetptKG0ggCG6Ruj

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults

  facebook:
    app_id: ENV['FB_ID']
    secret_key: ENV['FB_SECRET']
