defaults: &defaults

  facebook:
    app_id: ''
    secret_key: ''

  vk:
    api_key: ''
    api_secret: ''

  twitter:
    api_key: ''
    api_secret: ''

  google:
    client_id: ''
    client_secret: ''

development:
  <<: *defaults
test:
  <<: *defaults
staging:
  <<: *defaults
production:
  <<: *defaults
